[[SimpleBLE]]
arch = "aarch64"
git-tree-sha1 = "b00385c8e04284a2f010876b4c2e9f41ac0ce59c"
os = "macos"

    [[SimpleBLE.download]]
    sha256 = "7f3f7a035bcc833b2c8fc39292e2f80fa716187b28621a700ff4b9215126a3b2"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.aarch64-apple-darwin.tar.gz"
[[SimpleBLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f972450762226048da8b9345a54a6791004abcec"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "51322f2a37df4dfc6b79de270f4f0da71617d61e92b7ff0f701c725118ad8f88"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
git-tree-sha1 = "7d4c0523eb7e3ee8780c890b4f922416b756b139"
os = "macos"

    [[SimpleBLE.download]]
    sha256 = "f56e64aaf118122faa42490d6cedb2c56c28f7fdd4c18954c1c866bb41735e32"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.x86_64-apple-darwin.tar.gz"
[[SimpleBLE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2805ed266789d15180abf7691324c455839ae533"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "dcecbd146b98b2bf2e5f27ee71b6f3a2eee83ad9080a8a6e83c67a271a0ec359"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2805ed266789d15180abf7691324c455839ae533"
libc = "musl"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "dcecbd146b98b2bf2e5f27ee71b6f3a2eee83ad9080a8a6e83c67a271a0ec359"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SimpleBLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3949bac2e6c6770cbd54d7ecdea7f1ceb5caa95"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "4d0ebf68942d83cfe55146ccf2faf4e8a354213fc1569fd807c165247b44fb33"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3949bac2e6c6770cbd54d7ecdea7f1ceb5caa95"
libc = "musl"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "4d0ebf68942d83cfe55146ccf2faf4e8a354213fc1569fd807c165247b44fb33"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.i686-linux-musl-cxx11.tar.gz"
[[SimpleBLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e50aa7a51d55ab24bbaa16deb05f5e6cd7987d79"
os = "windows"

    [[SimpleBLE.download]]
    sha256 = "4f499e1538d8835df81b2fa73ae4bfaa23a3ea261c476203644034f69dd5005c"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea9c4fd55afea6c9c335963bb6bacd2ef3799df9"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "90b67648257121207a07a7ce081eed82d59a39a4c7ef280ce4ca4d6fa7e27130"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea9c4fd55afea6c9c335963bb6bacd2ef3799df9"
libc = "musl"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "90b67648257121207a07a7ce081eed82d59a39a4c7ef280ce4ca4d6fa7e27130"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc6a9b3a16b6025f8956c153718e9cf8fc95699c"
os = "windows"

    [[SimpleBLE.download]]
    sha256 = "f9551c7633dd9f0ce9d0dcfa7876e83c8060e4b1ddc593ae28f4f83ea27777a6"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v1.0.0+0/SimpleBLE.v1.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
