[[SimpleBLE]]
arch = "x86_64"
git-tree-sha1 = "4ab30299ba297bae945e9f696fdae51c7fff44b3"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "74bdfb85a181822bc281d01c8129d21bec77963f030ede0e5515f4d43546ab45"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.x86_64-linux-gnu.tar.gz"
[[SimpleBLE]]
arch = "aarch64"
git-tree-sha1 = "b00385c8e04284a2f010876b4c2e9f41ac0ce59c"
os = "macos"

    [[SimpleBLE.download]]
    sha256 = "7f3f7a035bcc833b2c8fc39292e2f80fa716187b28621a700ff4b9215126a3b2"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.aarch64-apple-darwin.tar.gz"
[[SimpleBLE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "153d555b5f93df32eeada7eefc1ee8012dcb5a3e"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "5838e5b31f3b133266db8f033e0ba574410cabf9876e140c8ff009b8b1219533"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f972450762226048da8b9345a54a6791004abcec"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "51322f2a37df4dfc6b79de270f4f0da71617d61e92b7ff0f701c725118ad8f88"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SimpleBLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd9f078c947e0cbe521a2520f0c4d00814e1233e"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "7c9e64a120d06d39396b684666081bda27cdbb0c70175d384e314704a88b336a"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.i686-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "508c113572fb2175d5924cbca924ab7a5e538385"
os = "windows"

    [[SimpleBLE.download]]
    sha256 = "0295865ade347568146f268c84aec0292b8f8c9d330a94d77684811305765724"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.i686-w64-mingw32-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
git-tree-sha1 = "7d4c0523eb7e3ee8780c890b4f922416b756b139"
os = "macos"

    [[SimpleBLE.download]]
    sha256 = "f56e64aaf118122faa42490d6cedb2c56c28f7fdd4c18954c1c866bb41735e32"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.x86_64-apple-darwin.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ab30299ba297bae945e9f696fdae51c7fff44b3"
libc = "glibc"
os = "linux"

    [[SimpleBLE.download]]
    sha256 = "74bdfb85a181822bc281d01c8129d21bec77963f030ede0e5515f4d43546ab45"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SimpleBLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bb9ca39c2e829ffb75f59d78e8be3d92622a940"
os = "windows"

    [[SimpleBLE.download]]
    sha256 = "4531d4babc81b4a9c8c0f8cca0debb8c798d36f464d3eb3a1cbdb67da1ff873e"
    url = "https://github.com/AwesomeQuest/SimpleBLE_jll/releases/download/SimpleBLE-v0.12.1+1/SimpleBLE.v0.12.1.x86_64-w64-mingw32-cxx11.tar.gz"
