# Autogenerated wrapper script for SimpleBLE_jll for aarch64-apple-darwin
export simpleble, simplecble

JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(simpleble, "@rpath/libsimpleble.0.dylib")
JLLWrappers.@declare_library_product(simplecble, "@rpath/libsimplecble.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        simpleble,
        "lib/libsimpleble.0.12.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/libsimplecble.0.12.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
