# Autogenerated wrapper script for SimpleBLE_jll for aarch64-linux-musl-cxx11
export simpleble, simplecble

JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(simpleble, "libsimpleble.so.1")
JLLWrappers.@declare_library_product(simplecble, "libsimplecble.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        simpleble,
        "lib/libsimpleble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/libsimplecble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
