# Autogenerated wrapper script for SimpleBLE_jll for armv6l-linux-musleabihf-cxx11
export libsimpleble, libsimplecble, simpleble, simplecble

using Dbus_jll
JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(libsimpleble, "libsimpleble.so.0")
JLLWrappers.@declare_library_product(libsimplecble, "libsimplecble.so.0")
JLLWrappers.@declare_library_product(simpleble, "libsimpleble.so.0")
JLLWrappers.@declare_library_product(simplecble, "libsimplecble.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Dbus_jll)
    JLLWrappers.@init_library_product(
        libsimpleble,
        "lib/libsimpleble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsimplecble,
        "lib/libsimplecble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simpleble,
        "lib/simpleble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/simplecble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
