# Autogenerated wrapper script for SimpleBLE_jll for x86_64-apple-darwin
export libsimpleble, libsimplecble, simpleble, simplecble

using Dbus_jll
JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(libsimpleble, "@rpath/libsimpleble.0.dylib")
JLLWrappers.@declare_library_product(libsimplecble, "@rpath/libsimplecble.0.dylib")
JLLWrappers.@declare_library_product(simpleble, "@rpath/libsimpleble.0.dylib")
JLLWrappers.@declare_library_product(simplecble, "@rpath/libsimplecble.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Dbus_jll)
    JLLWrappers.@init_library_product(
        libsimpleble,
        "lib/libsimpleble.0.12.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsimplecble,
        "lib/libsimplecble.0.12.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simpleble,
        "lib/simpleble.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/simplecble.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
