# Autogenerated wrapper script for SimpleBLE_jll for x86_64-w64-mingw32
export simpleble, simplecble

JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(simpleble, "simpleble.dll")
JLLWrappers.@declare_library_product(simplecble, "simplecble.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        simpleble,
        "bin\\simpleble.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "bin\\simplecble.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
