# Autogenerated wrapper script for SimpleBLE_jll for x86_64-unknown-freebsd
export simpleble, simpleble, simplecble, simplecble

using Dbus_jll
JLLWrappers.@generate_wrapper_header("SimpleBLE")
JLLWrappers.@declare_library_product(simpleble, "libsimpleble.so.0")
JLLWrappers.@declare_library_product(simpleble, "libsimpleble.so.0")
JLLWrappers.@declare_library_product(simplecble, "libsimplecble.so.0")
JLLWrappers.@declare_library_product(simplecble, "libsimplecble.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Dbus_jll)
    JLLWrappers.@init_library_product(
        simpleble,
        "lib/simpleble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simpleble,
        "lib/libsimpleble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/simplecble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        simplecble,
        "lib/libsimplecble.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
